#???????????????????root????????demo????????????
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/woc?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis??resources?mapper?????xml??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.example.woc.entity
#???8081
server:
  port: 8081
